

#mysql
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/t_tiger_db?useUnicode=true&characterEncoding=utf-8&useSSL=true  #连接字段
    username:  root
    password:  bdf7dd77
    type: com.alibaba.druid.pool.DruidDataSource

  #指定日志管理XML 配置
logging:
  config: classpath:log/logback.xml

  #mybatis-plus 配置  **代表任意目录
mybatis-plus:
  #指定访问路径
  mapper-locations: classpath*:com/tiger/common/**/*Mapper.xml
server:
  port: 8081
