#mysql
spring:
  #  datasource:
  #    url:  jdbc:mysql://localhost:3306/t_tiger_db?useUnicode=true&characterEncoding=utf-8&useSSL=true  #连接字段
  #    username:  root
  #    password:  bdf7dd77
  #    type: com.alibaba.druid.pool.DruidDataSource
  #

  application:
    name: commodity_user_service

  mvc:
    #出现错误时。直接抛出异常（便于异常统一处理 否则捕获不到404）
    throw-exception-if-no-handler-found: true
  resources:
    #不要为工程中的资源文件 建立映射
    add-mappings: false

#eureka 配置
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8081/eureka/     #当前服务注册到服务中心去 http为注册中心地址

  #指定日志管理XML 配置
logging:
  config: classpath:log/logback.xml
  #
#  mybatis-plus 配置  **代表任意目录
mybatis-plus:
  #    #指定访问路径.mapper
  mapper-locations: classpath*:com/tiger/user/commodity_user_service/dao/**/*Mapper.xml



server:
  port: 8083

